name: rakaan
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get_it: ^8.0.2
  injectable: ^2.5.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.14
  dartz: ^0.10.1
  internet_connection_checker_plus: ^2.5.2
  device_info_plus: ^11.1.1
  device_preview: ^1.2.0
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  flutter_native_splash: ^2.4.2
  shared_preferences: ^2.3.2
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  http: ^1.2.2
  fluttertoast: ^8.2.8
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  pull_to_refresh: ^2.0.0
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  firebase_crashlytics: ^4.1.4
  flutter_local_notifications: ^18.0.0
  share_plus: ^10.1.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  app_links: ^6.3.2
  country_code_picker_plus: ^0.0.9
  country_code_picker: ^3.1.0
  flutter_launcher_icons: ^0.14.1
  intl: ^0.20.0
  custom_info_window: ^1.0.1
  dotted_border: ^2.1.0
  skeletonizer: ^1.4.2
  moyasar: ^2.0.13
  pusher_channels_flutter:
  flutter_polyline_points: ^2.0.0
  archive: ^3.6.1
  flutter_html: ^3.0.0

dependency_overrides:
  path: ^1.9.1
  web: ^1.0.0
  intl: ^0.20.0




dev_dependencies:
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icons/app_icon.jpg"
  min_sdk_android: 21   # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icons/app_icon.jpg"



flutter:


  uses-material-design: true


  assets:
    - assets/translations/
    - assets/images/
    - assets/images/icons/
    - assets/jsons/


  fonts:
    - family: cairo
      fonts:

        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700


